#include "GltfToMesh.hpp"

#include <CesiumGltf/AccessorView.h>
#include <CesiumGltf/AccessorUtility.h>
#include <CesiumGltf/VertexAttributeSemantics.h>
#include <CesiumGltfContent/GltfUtilities.h>

#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/quaternion.hpp>

#include <cstring>

namespace reactnativecesium {

std::vector<TilePrimitive>
GltfToMesh::convert(const CesiumGltf::Model& model,
                    const glm::dmat4& tileTransform) {
  std::vector<TilePrimitive> results;

  // Apply CESIUM_RTC and glTF Y-up adjustment (same as reference implementation).
  glm::dmat4 rootTransform = tileTransform;
  rootTransform = CesiumGltfContent::GltfUtilities::applyRtcCenter(model, rootTransform);
  rootTransform = CesiumGltfContent::GltfUtilities::applyGltfUpAxisTransform(model, rootTransform);

  model.forEachPrimitiveInScene(
      -1,
      [&results, &rootTransform](
          const CesiumGltf::Model& gltf,
          const CesiumGltf::Node& /*node*/,
          const CesiumGltf::Mesh& /*mesh*/,
          const CesiumGltf::MeshPrimitive& primitive,
          const glm::dmat4& nodeTransform) {

        // Only handle triangle-based primitives.
        switch (primitive.mode) {
        case CesiumGltf::MeshPrimitive::Mode::TRIANGLES:
        case CesiumGltf::MeshPrimitive::Mode::TRIANGLE_STRIP:
        case CesiumGltf::MeshPrimitive::Mode::TRIANGLE_FAN:
          break;
        default:
          return;
        }

        const CesiumGltf::PositionAccessorType posAccessor =
            CesiumGltf::getPositionAccessorView(gltf, primitive);
        if (posAccessor.status() != CesiumGltf::AccessorViewStatus::Valid ||
            posAccessor.size() <= 0)
          return;

        const glm::dmat4 worldTransform = rootTransform * nodeTransform;
        const int64_t vertexCount       = posAccessor.size();

        TilePrimitive prim;
        prim.positionsEcef.reserve(static_cast<size_t>(vertexCount));

        for (int64_t i = 0; i < vertexCount; ++i) {
          const auto& p = posAccessor[i];
          const glm::dvec3 local(p.value[0], p.value[1], p.value[2]);
          prim.positionsEcef.push_back(
              glm::dvec3(worldTransform * glm::dvec4(local, 1.0)));
        }

        // Extract overlay UV coordinates (_CESIUMOVERLAY_0 is generated by
        // Cesium Native when a raster overlay is active on the tileset).
        const auto uvIt = primitive.attributes.find("_CESIUMOVERLAY_0");
        if (uvIt != primitive.attributes.end() && uvIt->second >= 0) {
          CesiumGltf::AccessorView<CesiumGltf::AccessorTypes::VEC2<float>> uvView(gltf, uvIt->second);
          if (uvView.status() == CesiumGltf::AccessorViewStatus::Valid &&
              uvView.size() == vertexCount) {
            prim.uvs.reserve(static_cast<size_t>(vertexCount));
            for (int64_t i = 0; i < vertexCount; ++i) {
              prim.uvs.push_back(glm::vec2(uvView[i].value[0], uvView[i].value[1]));
            }
          }
        }

        // Expand index buffer → flat uint32 triangle list.
        const CesiumGltf::IndexAccessorType idxAccessor =
            CesiumGltf::getIndexAccessorView(gltf, primitive);

        const int64_t srcIdxCount =
            (primitive.indices >= 0)
                ? std::visit(CesiumGltf::CountFromAccessor{}, idxAccessor)
                : vertexCount;

        int64_t faceCount = 0;
        switch (primitive.mode) {
        case CesiumGltf::MeshPrimitive::Mode::TRIANGLES:
          faceCount = srcIdxCount / 3;
          break;
        case CesiumGltf::MeshPrimitive::Mode::TRIANGLE_STRIP:
        case CesiumGltf::MeshPrimitive::Mode::TRIANGLE_FAN:
          faceCount = std::max<int64_t>(0, srcIdxCount - 2);
          break;
        default:
          break;
        }

        prim.indices.reserve(static_cast<size_t>(faceCount * 3));
        for (int64_t fi = 0; fi < faceCount; ++fi) {
          const std::array<int64_t, 3> face = std::visit(
              CesiumGltf::IndicesForFaceFromAccessor{
                  fi, vertexCount, primitive.mode},
              idxAccessor);
          if (face[0] < 0 || face[1] < 0 || face[2] < 0 ||
              face[0] >= vertexCount || face[1] >= vertexCount ||
              face[2] >= vertexCount)
            continue;
          prim.indices.push_back(static_cast<uint32_t>(face[0]));
          prim.indices.push_back(static_cast<uint32_t>(face[1]));
          prim.indices.push_back(static_cast<uint32_t>(face[2]));
        }

        if (!prim.indices.empty()) {
          results.push_back(std::move(prim));
        }
      });

  return results;
}

} // namespace reactnativecesium
